name: beholder

packages:
  - packages/*
  - examples/*

scripts:
  test:
    run: melos run test:dart --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec  -c 1 --fail-fast -- "dart test"
    description: Run Dart tests for a specific package in this project.
    packageFilters:
      flutter: false
      dirExists: test
