name: beholder
description:
  State Management inspired by MobX.
  Yet another MVVM implementation.
  Reinventing the wheel, but with a twist.
version: 0.4.0
repository: https://github.com/AlexanderFarkas/beholder/tree/main/packages/beholder

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
